<Project>

  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

  <PropertyGroup Label="Build">
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RootNamespace>Schema.NET</RootNamespace>
  </PropertyGroup>

  <ItemGroup Label="Source Generator Options">
    <CompilerVisibleProperty Include="IncludePendingSchemaObjects" />
  </ItemGroup>

  <ItemGroup Label="Package References">
    <PackageReference Include="DotNet.ReproducibleBuilds" PrivateAssets="all" Version="1.2.39" />
    <PackageReference Include="System.Text.Json" Version="10.0.0"/>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0"/>
  </ItemGroup>

  <ItemGroup Label="Files">
<!--    <None Include="..\..\Images\Icon.png" Pack="true" PackagePath="\" />-->
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
