<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Build">
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>

  <ItemGroup Condition="'$(ForkVersion)' == ''">
    <PackageReference Include="Schema.NET" Version="13.0.0"/>
  </ItemGroup>

  <ItemGroup Condition="'$(ForkVersion)' != ''">
    <PackageReference Include="SchemaDotNet" Version="$(ForkVersion)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
  </ItemGroup>

</Project>
